require "generators/erb/webauthn_authentication/webauthn_authentication_generator"

module Tailwindcss
  module Generators
    class WebauthnAuthenticationGenerator < Erb::Generators::WebauthnAuthenticationGenerator
      hide!
      source_root File.expand_path("../templates", __FILE__)

      # The session view is generated by the Rails authentication generator and,
      # in a tailwindcss app, styled by tailwindcss-rails — wrapping its contents
      # in a centered `<div class="mx-auto md:w-2/3 w-full">`. We inject the passkey
      # form as the last child of that wrapper (before its closing `</div>`) so it
      # sits below the email/password form rather than becoming a sibling flex item.
      def inject_into_rails_session_view
        inject_into_file "app/views/sessions/new.html.erb", before: /^<\/div>\s*\z/ do
          <<~ERB.indent(2)
            <%= form_with(
              scope: :session,
              url: webauthn_session_path,
              method: :post,
              class: "contents",
              data: {
                controller: "webauthn-credentials",
                action: "webauthn-credentials#get:prevent",
                "webauthn-credentials-options-url-value": get_options_webauthn_session_path,
              }) do |f| %>
                <%= f.hidden_field :public_key_credential, data: { "webauthn-credentials-target": "credentialHiddenInput" } %>
                <div class="my-5">
                  <%= f.submit "Sign In with Passkey", disabled: true, data: { "webauthn-credentials-target": "submitButton" }, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
                </div>
            <% end %>
          ERB
        end
      end
    end
  end
end
